### ISSUE TITLE
Please delete this file or add copyright headers

### ISSUE THREAD

**Issue by klange** [MarcoCicognani/MeetiX-OS-Project#1]
Hi Marco,

I occasionally search for unique symbol names from my projects on Github to find derivative works and validate license compliance. While doing so, I found that your repository contains a copy of my dynamic linker source without license information. I suspect you were using it as an educational reference while building your own loader and committed it at that time. If you could remove this file from your repository, or add the relevant copyright information from [the original license](https://github.com/klange/toaruos/blob/master/LICENSE) it would be greatly appreciated. I hope my code has been useful to you (though my dynamic loader is a terrible hack, so hopefully you didn't follow it too closely)!

https://github.com/MarcoCicognani/MeetiX-OS-Project/blob/69763c6c3caeefb322c065d3d3c74afafebdb790/source/userspace/servers/spawner/linker.c

**Comment by MarcoCicognani** [comment]
Hi Kevin,
I'm so sorry. I have for the moment deleted the file, which I wrongly uploaded a few months ago.
As you said i had taken it as an example to develop my dynamic loader. But i don't understand why you said your dynlinker is a terrible hack?

**Comment by klange** [comment]
It's missing a lot of important functionality related to symbol resolution order. It only fulfills enough of the ELF specification to get my own userspace working, and a bit more to get Python loading dynamic C modules.
