### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by CheyenneForbes** [MarcoCicognani/MeetiX-OS-Project#2]

**Comment by CheyenneForbes** [comment]
Is this project still active?

**Comment by CheyenneForbes** [comment]
Also, why didnt you go with a hybrid kernel?

**Comment by MarcoCicognani** [comment]
Hi CheyenneForbes, yes, my project is still active, but due to some personal problems and commitments, development proceeds very slowly. I have not yet reached a new stable release

**Comment by CheyenneForbes** [comment]
How hard would it be to switch this to a hybrid kernel?

**Comment by MarcoCicognani** [comment]
What do you mean for hybrid kernel? Userspace kernel servers and kernel relocatable modules?

**Comment by CheyenneForbes** [comment]
yes

**Comment by MarcoCicognani** [comment]
Mmmh, make EvangelionNG, the MeetriX's kernel, an Hybrid Kernel is not a goal of the project, i'm at work to the dynamic linker

**Comment by CheyenneForbes** [comment]
If EvangelionNG was hybrid MeetriX could one day rob windows and osx of users :)

**Comment by MarcoCicognani** [comment]
The main problem is that EvangelionNG is not unix like, and there is no support for standard syscalls to perform generic access to a driver like unix for devices (with the: open, close, write, close, ioctl...ecc syscalls) because MeetiX have not the devices files :-(

**Comment by CheyenneForbes** [comment]
is marco.cicognani@btstore.com still the email address to get to you?

**Comment by MarcoCicognani** [comment]
Yes

**Comment by maxdev1** [comment]
It's not really a problem that the kernel is not unix-like, actually the design already plans to have device files (a hard disk is a device too after all).

The `fs_delegate_tasked` in Ghost (or `FsDelegateTasked` in EvNG) is a generic interface that allows the implementation of user space drivers. Those could be a hard disk, but also any other device. In the fs model, you just need a new node with this type of delegate & a handler process to perform the actual communication.

**Comment by CheyenneForbes** [comment]
I sent you an email
