### ISSUE TITLE
How to build Meetix OS

### ISSUE THREAD

**Issue by UtkrishtTech** [MarcoCicognani/MeetiX-OS-Project#3]
Please give instructions on how to build Meetix os

**Comment by MarcoCicognani** [comment]
Sure man, sorry but my documentation is really poor.
Well, first you have to be sure to have installed: Qemu, gmp, mpfr, bash, GCC and G++.
Then go to toolchain directory and type: sudo bash build.sh, this will download, build and install on /opt/MeetiXOSProject the toolchains.
For last type on source directory: bash b eva && bash b user all && bash b repack to build the kernel, the userspace and create an image to boot
