### ISSUE TITLE
How to build 

### ISSUE THREAD

**Issue by dimutch833** [MarcoCicognani/MeetiX-OS-Project#5]
what  libraries to need be install    i type in terminal   sudo bash build.sh and i have  binutils build failed
Xubuntu 64 bit 2gb of ram

**Comment by bikeroleg** [comment]
Have you seen #3 ? Also you may [download the iso](https://www.meetixos.org/download/) from the official site if you don't _really_ need to build the OS. Actually, most ports' ``tar``s requred for the installation aren't available anymore at the meetixos.org so I don't think it's possible to build the OS now.

**Comment by MarcoCicognani** [comment]
Hi, sorry but at the moment this implementation is not longer supported and developed. Currently I working to a complete reimplementation of the system that soon as possible i will merge to this repository. I promise that in these following day i take a moment to fix build errors of this legacy version
